---
dependency:
  name: galaxy
driver:
  name: docker
lint: ansible-lint
platforms:
  - name: centos-7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    network_mode: host
    env:
      http_proxy: http://localhost:8888
      https_proxy: http://localhost:8888
  - name: centos-8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    network_mode: host
    env:
      http_proxy: http://localhost:8888
      https_proxy: http://localhost:8888
provisioner:
  name: ansible
verifier:
  name: ansible
